### ISSUE TITLE
多谢大佬开源此项目!

### ISSUE THREAD

**Issue by adinlead** [Xqh233/DiyibanzhuSpider#2]
其实我本来想自己写一个爬虫，都已经写了一些代码了，但是回头一想，说不定有人已经写过了呢？于是就来Github碰碰运气，没想到真的叫我碰到了你！嘿嘿，大佬牛逼！
不过有一说一，感觉大佬的代码写的有些不符合Python3规范，不知道是大佬的代码风格还是从其他语言带来的习惯。我Fork了一份代码，并且重新整理了一遍代码，使其更加符合Python3规范，如果能入得了大佬法眼，就合并一下吧。

**Comment by wzj042** [comment]
其实本来想用java写的，但是java太繁琐了，只好自己边搜边写了个🤣

**Comment by adinlead** [comment]
哈哈哈，我就说嘛！这个代码风格跟Java非常想！
我本职也是做Java开发的，但是我有强迫症，看到IDE里报警告就难受🤣🤣
