### ISSUE TITLE
好像寄了，使用谷歌就会被疯狂重定向，但是用火狐能进首页，点击小说的详情页的时候进不去

### ISSUE THREAD

**Issue by zaimatest** [Xqh233/DiyibanzhuSpider#3]
出现了 Sorry, you have been blocked
ou are unable to access 01bzvip2.cc
的页面，寄

**Comment by wzj042** [comment]
疯狂重定向可以试试清除cookies，被ban了我还没试过定位不出问题。在锐意修bug中🤔

**Comment by zaimatest** [comment]
不是cookies的问题，我试了一下，用selenium驱动火狐可以进入主页，但是随便点击一下就会被Cloudflare给ban掉，显示Sorry, you have been blocked，如果换谷歌就出现疯狂重定向，然后我挂了一个sslvpn就可以用谷歌进了，怀疑是Cloudflare检测SSL

**Comment by wzj042** [comment]
似乎是被ban ip了，我刚才调试的时候也疯狂重定向。然后开虚拟机就能进去，过了1个小时我现在测试又能正常进入页面了。还没测出来是高频率访问导致还是被检测到了爬虫行为，我想想咋办吧🤔

**Comment by zaimatest** [comment]
老哥，请教一下，他文本里面的图片是从哪里获取的？萌新看代码有点看不懂
更新-----------------------
看了注释了解了
