### ISSUE TITLE
网页解析失败

### ISSUE THREAD

**Issue by mj17shAlice** [Xqh233/DiyibanzhuSpider#4]
如图所示
<img width="1063" alt="Snipaste_2023-02-18_11-10-02" src="https://user-images.githubusercontent.com/56729639/219828745-9cea0a3c-bffb-48c9-886e-62669a678d63.png">

**Comment by wzj042** [comment]
关掉代理试试，第一版主有的页面可以开代理有的不行。这个我也不太清楚怎么识别。如果你正常浏览器可以打开解析不了再看看吧🤔
